name: s3mp-dev-venv
channels:
  - conda-forge
  - defaults
dependencies:
  - aioboto3
  - boto3
  - boto3-stubs
  - botocore
  - future
  - mypy-boto3-s3
  - pre-commit
  - pip
  - pyparsing
  - pyproj
  - pytest
  - python
  - setuptools
  - tqdm
