name: s3mp-venv
channels:
  - conda-forge
  - defaults
dependencies:
  - aioboto3
  - boto3
  - boto3-stubs
  - botocore
  - future
  - mypy-boto3-s3
  - numpy
  - pip
  - pyparsing
  - pyproj
  - python
  - setuptools
  - tqdm
  - pip: 
    - opencv-python