name: Tag It

# Controls when the workflow will run
on:
  workflow_dispatch:
  pull_request:
    types: [ closed ] 
    branches: [ master ]


# Tag jobs
jobs:
  tag-pr: 
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3
      - name: Tag It
        run: | 
          < S3MP/_version.py sed -n 's/^__version__ = \"\(.*\)\"$/v\1/p'
          version=$(< S3MP/_version.py sed -n 's/^__version__ = \"\(.*\)\"$/v\1/p')
          echo "version: $version"
          git tag $version
          git push -u origin $version
